#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello world!" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html 
sudo sed -i 's|server_name _;|server_name _;\n\terror_page 404 /404.html;|' /etc/nginx/sites-available/default
sudo sed -i 's|server_name _;|server_name _;\n\tadd_header X-Served-By $HOSTNAME;|' /etc/nginx/sites-available/default
sudo service nginx restart
