#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi


file="$1"
key="$4"
user="$3"
host="$2"


scp -o StrictHostKeyChecking=no -i "$key" "$file" "$user@$host:~/"
